version: '3.3'
services:
  grafana:
    image: grafana/grafana:latest
    mem_limit: 100m
    container_name: grafana
    restart: unless-stopped
      #ports:
      #- "3001:3000"
    networks:
      - caddynet
    volumes:
      - ./data/grafana/data:/var/lib/grafana
      - ./data/grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PW}

  influxdb:
    image: influxdb:latest
    mem_limit: 250m
    container_name: influxdb
    restart: unless-stopped
      #ports:
      #- "8086:8086"
    networks:
      - caddynet
    volumes:
      - ./data/influxdb/data:/var/lib/influxdb2
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
networks:
  caddynet:
    external: true
