version: '3.7'

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    environment:
      - VIRTUAL_HOST=nextcloud.dlavezzoli.local
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
    volumes:
      - ./data/nextcloud:/var/www/html
    networks:
      - caddynet
#    restart: unless-stopped

  db:
    image: mariadb
    container_name: nextcloud_db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - caddynet
#    restart: unless-stopped

networks:
  caddynet:
    external: true
